version: "3.8"
services:
  # Database from here https://hub.docker.com/_/mysql
  db:
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwordmu
    networks:
      - mysql-phpmyadmin

  # phpmyadmin from here https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwordmu
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"

volumes:
  db_data: